### ISSUE TITLE
Brain zu Leistungssteuerung Kommunikation

### ISSUE THREAD

**Issue by pszabo1** [halwaxt/bic4-ese#10]

**Comment by halwaxt** [comment]
Der erste Entwurf sieht eine Kommunikation über Telnet vor. Sollte sich dieser Ansatz als zu ineffizient bzw. langsam herausstellen, können wir immer noch auf ein binäres Protokoll umschwenken.

Die erste Implementierung sieht die Steuerung der Leistung über das Kommando "Pxxx" vor. xxx steht dabei für die Leistung im Bereich von 0% bis 100% wobei das Format immer dreistellig mit führenden Nullen sein muss.

**Comment by pszabo1** [comment]
Ist an und für sich entwickelt. Wenn hierzu noch weiteres offen ist können wir ja einen anderen Case aufmachen (oder das außerhalb abwickeln)
