### ISSUE TITLE
Test mechanischer Sensor mit einem Mikroschalter

### ISSUE THREAD

**Issue by halwaxt** [halwaxt/bic4-ese#2]
Zur Unterteilung der Strecke in Sektoren werden Sensoren benötigt. Wir beginnen mit mechanischen Sensoren wie z.B. einem [Mikroschalter](https://www.conrad.at/de/mikroschalter-250-vac-6-a-1-x-ein-ein-cherry-switches-db1c-b1ld-tastend-1-st-703766.html?sc.ref=Product%20Details). Über einen GPIO soll zuverlässig das Vorbeifahren des Autos auf der Bahn erkannt werden.

**Comment by pszabo1** [comment]
#6 - daher Close
