### ISSUE TITLE
Leistungssteuerung ansprechen und Informationen austauschen

### ISSUE THREAD

**Issue by pszabo1** [halwaxt/bic4-ese#4]
Die Leistungssteuerung soll via PWM ansprechbar sein und die Leistung dahingehend eingestellt werden können.

**Comment by pszabo1** [comment]
@halwaxt soweit mal erledigt, oder? kann man den closen?

**Comment by halwaxt** [comment]
Leisungssteuerung via PWM funktioniert soweit, allerdings gibt es bisher keine Interaktion. D.h., der Duty Teil ist hart kodiert.
