### ISSUE TITLE
LAN Integration

### ISSUE THREAD

**Issue by pszabo1** [halwaxt/bic4-ese#5]
Mittels Kommunikationsschnittstelle soll ein Datenaustausch zwischen Board und Webservice möglich sein.

**Comment by halwaxt** [comment]
Im NDK des RTOS gibt es einiges zu konfigurieren. Wir sollten überlegen, welches bereits existierende Protokoll (Telnet, http) für unsere Zwecke optimal ist.

**Comment by halwaxt** [comment]
Nach dem Studium der NDK Dokumentation erscheint mir die Kommunikation via http Modul doch einfacher als die bisher präferierte Telnet Variante. Vieles run um http bringt RTOS schon mit.

**Comment by halwaxt** [comment]
Die LAN Integration wurde über UDP Broadcasts gelöst. Sowohl die Sektor/Rundenzeiten als auch Änderungen an den PowerValues kommen über UDP. Das ist vor Allem nützlich, wenn man ACDC in Umgebungen betreiben will, die sich von den IP Settings start unterscheiden.
